
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
    
      - name: Install dependencies
        run: dotnet restore IT.sln
    
      - name: Build
        run: dotnet build IT.sln --configuration Release --no-restore 
    
      - name: Test System
        run: dotnet test tests/IT.Tests/IT.Tests.csproj
            
      - name: Publish IT
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT/IT.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
        
      - name: Publish IT.Memory
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Memory/IT.Memory.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
        
      - name: Publish IT.Bcl
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Bcl/IT.Bcl.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.PubSub
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.PubSub/IT.PubSub.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false

      - name: Publish IT.PubSub.Redis
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.PubSub.Redis/IT.PubSub.Redis.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false

      - name: Publish IT.Security.Cryptography
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Security.Cryptography/IT.Security.Cryptography.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Security.Cryptography.Xml
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Security.Cryptography.Xml/IT.Security.Cryptography.Xml.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Security.Cryptography.Gost
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Security.Cryptography.Gost/IT.Security.Cryptography.Gost.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Security.Cryptography.JinnServer
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Security.Cryptography.JinnServer/IT.Security.Cryptography.JinnServer.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Security.Cryptography.BouncyCastle
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Security.Cryptography.BouncyCastle/IT.Security.Cryptography.BouncyCastle.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Pdf
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Pdf/IT.Pdf.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Pdf.DinkToPdf
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Pdf.DinkToPdf/IT.Pdf.DinkToPdf.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Pdf.PDFSharp
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Pdf.PDFSharp/IT.Pdf.PDFSharp.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Working
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Working/IT.Working.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Working.Redis
        uses: pairbit/publish-nuget@v2.5.9
        with:
            PROJECT_FILE_PATH: src/IT.Working.Redis/IT.Working.Redis.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
