
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
    
      - name: Install dependencies
        run: dotnet restore IT.sln
    
      - name: Build
        run: dotnet build IT.sln --configuration Release --no-restore 
    
      - name: Tests
        run: dotnet test src/IT.Tests/IT.Tests.csproj
        
      - name: Publish IT.Bcl
        uses: Elskom/publish-nuget@main
        with:
            PROJECT_FILE_PATH: src/IT.Bcl/IT.Bcl.csproj
            PACKAGE_PATH: artifacts/
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
   
      - name: Publish IT
        uses: Elskom/publish-nuget@main
        with:
            PROJECT_FILE_PATH: src/IT/IT.csproj
            PACKAGE_PATH: artifacts/
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.AspNet
        uses: Elskom/publish-nuget@main
        with:
            PROJECT_FILE_PATH: src/IT.AspNet/IT.AspNet.csproj
            PACKAGE_PATH: artifacts/
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            
      - name: Publish IT.Security.Cryptography.JinnServer
        uses: Elskom/publish-nuget@main
        with:
            PROJECT_FILE_PATH: src/IT.Security.Cryptography.JinnServer/IT.Security.Cryptography.JinnServer.csproj
            PACKAGE_PATH: artifacts/
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
