
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
    
      - name: Install dependencies
        run: dotnet restore IT.sln
    
      - name: Build
        run: dotnet build IT.sln --configuration Release --no-restore 
    
      - name: Test System
        run: dotnet test tests/IT.Tests.System/IT.Tests.System.csproj
            
      - name: Test Generation
        run: dotnet test tests/IT.Tests.Generation/IT.Tests.Generation.csproj
        
      - name: Test Serialization
        run: dotnet test tests/IT.Tests.Serialization/IT.Tests.Serialization.csproj
        
      - name: Test Security.Cryptography
        run: dotnet test tests/IT.Tests.Security.Cryptography/IT.Tests.Security.Cryptography.csproj
        
      - name: Publish IT.Memory
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Memory/IT.Memory.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
        
      - name: Publish IT.Bcl
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Bcl/IT.Bcl.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Locking
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Locking/IT.Locking.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Locking.Redis
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Locking.Redis/IT.Locking.Redis.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true

      - name: Publish IT.Generation
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Generation/IT.Generation.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Generation.KGySoft
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Generation.KGySoft/IT.Generation.KGySoft.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Serialization
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Serialization/IT.Serialization.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Serialization.Json
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Serialization.Json/IT.Serialization.Json.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Serialization.Utf8Json
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Serialization.Utf8Json/IT.Serialization.Utf8Json.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
