
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
    
      - name: Install dependencies
        run: dotnet restore IT.sln
    
      - name: Build
        run: dotnet build IT.sln --configuration Release --no-restore 
    
      - name: Tests
        run: dotnet test tests/IT.Tests/IT.Tests.csproj
        
      - name: Publish System.Memory.Extensions
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Memory/IT.Memory.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
        
      - name: Publish IT.Bcl
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Bcl/IT.Bcl.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Locking
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Locking/IT.Locking.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
            
      - name: Publish IT.Locking.Redis
        uses: pairbit/publish-nuget@v2.5.6
        with:
            PROJECT_FILE_PATH: src/IT.Locking.Redis/IT.Locking.Redis.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: false
            INCLUDE_SYMBOLS: true
